sudo: false

language: php

branches:
  only:
  - master
  
php:
  - 7.1.0

addons:
  ssh_known_hosts: travis-tp5-prod.web.freenat.club
  
cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.cache/phan-ast/build"
  
before_install:
  - openssl aes-256-cbc -K $encrypted_0b64e68e6f78_key -iv $encrypted_0b64e68e6f78_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host travis-tp5-prod.web.freenat.club\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - pecl install ast-1.0.1
  - php -m
  - composer self-update

install:
  - zip -r --exclude='*.git*' --exclude='*.zip' --exclude='*.travis.yml' ThinkPHP_Core.zip .
  - composer install --no-dev --no-interaction --ignore-platform-reqs
  - composer require --ignore-platform-reqs phan/phan
  - zip -r --exclude='*.git*' --exclude='*.zip' --exclude='*.travis.yml' ThinkPHP_Full.zip .
  - chmod -R 777 ./
  - ls -al

script:
  - ./vendor/bin/phan --progress-bar
  - ./think unit

after_success:
  - scp ThinkPHP_Full.zip root@travis-tp5-prod.web.freenat.club:~/
  - ssh root@travis-tp5-prod.web.freenat.club 'mkdir -p indoor-server'

deploy:
  provider: releases
  api_key:
    secure: TSF6bnl2JYN72UQOORAJYL+CqIryP2gHVKt6grfveQ7d9rleAEoxlq6PWxbvTI4jZ5nrPpUcBUpWIJHNgVcs+bzLFtyh5THaLqm39uCgBbrW7M8rI26L8sBh/6nsdtGgdeQrO/cLu31QoTzbwuz1WfAVoCdCkOSZeXyT/CclH99qV6RYyQYqaD2wpRjrhA5O4fSsEkiPVuk0GaOogFlrQHx+C+lHnf6pa1KxEoN1A0UxxVfGX6K4y5g4WQDO5zT4bLeubkWOXK0G51XSvACDOZVIyLdjApaOFTwamPcD3S1tfvuxRWWvsCD5ljFvb2kSmx5BIBNwN80MzuBmrGIC27XLGOxyMerwKxB6DskNUO9PflKHDPI61DRq0FTy1fv70SFMSiAtUv9aJRT41NQh9iJJ0vC8dl+xcxrWIjU1GG6+l/ZcRqVx9V1VuGQsLKndGhja7SQ+X1slHl76fRq223sMOql7MFCd0vvvxVQ2V39CcFKao/LB1aPH3VhODDEyxwx6aXoTznvC/QPepgWsHOWQzKj9ftsgDbsNiyFlXL4cu8DWUty6rQy8zT2b4O8b1xjcwSUCsy+auEjBamzQkMJFNlZAIUrukL/NbUhQU37TAbwsFyz7X0E/u/VMle/nBCNAzgkMwAUjiHM6FqrKKBRWFbPrSIixjfjkCnrMEPw=
  file:
  - ThinkPHP_Core.zip
  - ThinkPHP_Full.zip
  skip_cleanup: true
  on:
    tags: true
