version: "3"
services:

  nginx:
    build: ./docker/nginx
    container_name: nginx
    depends_on: 
      - php
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${APPLICATION}:/var/www/html:rw
      - ${LOG_PATH}:/var/log/nginx:rw
      - ${NGINX_VHOST_PATH}:/etc/nginx/conf.d/:ro
      - ${NGINX_CONFIG_FILENAME}:/etc/nginx/nginx.conf:ro
    restart: always
      
  php:
    build: ./docker/php
    container_name: php
    expose:
      - 9000
    volumes:
      - ${APPLICATION}:/var/www/html:rw
      - ${LOG_PATH}:/var/log:rw
      - ${PHP_INI_PATH}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_PATH}:/usr/local/etc/php-fpm.d/www.conf:rw
        
      